#!/usr/bin/env bash
if [[ -n "$1" ]]
then
	echo "# $1" >> README.md
	git init
	git add README.md
	git commit -m "first commit"
	git branch -M main
	git remote add origin https://github.com/Hegeldirkk/$1.git
	git push -u origin main
fi
